export const CATEGORIES = {
	art: 'art',
	business: 'business',
	childrens: 'childrens',
	classics: 'classics',
	fantasy: 'fantasy',
	fiction: 'fiction',
	graphicBooksAndManga: 'graphicBooksAndManga',
	horror: 'horror',
	lgbtq: 'lgbtq',
	mystery: 'mystery',
	nonFiction: 'nonFiction',
	philosophy: 'philosophy',
	poetry: 'poetry',
	religion: 'religion',
	romance: 'romance',
	scienceFiction: 'scienceFiction',
	thriller: 'thriller',
	youngAdult: 'youngAdult',
} as const
