enum BestSellersListName {
	FICTION
	NON_FICTION
	YOUNG_ADULT
	CHILDRENS
	GRAPHIC_BOOKS_AND_MANGA
}

enum Category {
	FICTION
	NON_FICTION
	ROMANCE
	YOUNG_ADULT
	GRAPHIC_BOOKS_AND_MANGA
	FANTASY
	HORROR
	MYSTERY
	THRILLER
	SCIENCE_FICTION
	ART
	PHILOSOPHY
	RELIGION
	CHILDRENS
	CLASSICS
	BUSINESS
	POETRY
	LGBTQ
}

type BookSummary {
	id: ID!
	isGoogleId: Boolean!
	title: String!
	authors: [String!]
	cover: String
}

type BookPreview {
	id: ID!
	isGoogleId: Boolean!
	title: String!
	authors: [String!]
	cover: String
	publishedYear: Int
	pageCount: Int
	categories: [String!]
	isbn: [String!]
}

type BookDetails {
	id: ID!
	isGoogleId: Boolean!
	title: String!
	authors: [String!]
	cover: String
	subtitle: String
	description: String
	pageCount: Int
	categories: [String!]
	publishedDate: String
	language: String
	publisher: String
}

type BestSellersList {
	id: ID!
	listName: BestSellersListName!
	latestUpdate: Int!
	books: [BookSummary!]!
}

input BookDetailsInput {
	id: ID
	title: String
	author: String
	isbn: [String!]
}

type Query {
	bestSellersLists: [BestSellersList!]
	booksByCategory(category: Category!): [BookPreview!]
	searchBooks(query: String!): [BookPreview!]
	bookDetails(book: BookDetailsInput!): BookDetails
}
