enum BestSellersListName {
	FICTION
	NON_FICTION
	YOUNG_ADULT
	CHILDRENS
	GRAPHIC_BOOKS_AND_MANGA
}

enum Category {
	FICTION
	NON_FICTION
	ROMANCE
	YOUNG_ADULT
	GRAPHIC_BOOKS_AND_MANGA
	FANTASY
	HORROR
	MYSTERY
	THRILLER
	SCIENCE_FICTION
	ART
	PHILOSOPHY
	RELIGION
	CHILDRENS
	CLASSICS
	BUSINESS
	POETRY
	LGBTQ
}

type BookSummary {
	id: ID!
	isExternalId: Boolean!
	title: String!
	authors: [String!]
	cover: String
	isbn10: String
	isbn13: String
}

type BookPreview {
	id: ID!
	isExternalId: Boolean!
	title: String!
	authors: [String!]
	cover: String
	isbn10: String
	isbn13: String
	publishedYear: Int
	pageCount: Int
	categories: [String!]
	contentWarnings: [String!]
}

type BookDetails {
	id: ID!
	isExternalId: Boolean!
	title: String!
	authors: [String!]
	cover: String
	isbn10: String
	isbn13: String
	publishedYear: Int
	pageCount: Int
	categories: [String!]
	contentWarnings: [String!]
	characters: [String!]
	subtitle: String
	description: String
	publishedDate: String
	language: String
	publisher: String
	relatedBooks: [BookSummary!]
}

type BestSellersList {
	id: ID!
	listName: BestSellersListName!
	latestUpdate: String!
	books: [BookSummary!]!
}

type SearchBooksResult {
	totalCount: Int!
	books: [BookPreview!]
}

input BookDetailsInput {
	id: ID!
	isExternalId: Boolean!
	title: String!
	authors: [String!]
	isbn10: String
	isbn13: String
}

type Query {
	bestSellersLists: [BestSellersList!]
	booksByCategory(category: Category!): [BookPreview!]
	searchBooks(query: String!, limit: Int): SearchBooksResult!
	bookDetails(book: BookDetailsInput!): BookDetails
}
